"use strict";
let course = "web3";
console.log(course == "web3" ? "i predict " : "i predict ");
console.log(course == "web3"); // print true or false 
let batch = 43;
console.log(batch == 43 ? "i predict " : "i predict ");
console.log(batch == 43);
let city = "lahore";
console.log(city == "lahore" ? "i predict " : "i predict ");
console.log(city == "lahore");
let day = "sunday";
console.log(day == "sunday" ? "i predict " : "i predict ");
console.log(day == "sunday");
let ecenter = "umt";
console.log(ecenter == "umt" ? "i predict " : "i predict ");
console.log(ecenter == "umt");
console.log("now false test");
let ager = "yes";
console.log(ager == "no" ? "i predict" : "i predict");
console.log(ager == "no");
let gender = "male";
console.log(gender == "any" ? "i predict " : "i predict ");
console.log(gender == "any");
let time = "10 pm";
console.log(time == "2 pm," ? "i predict " : "i predict ");
console.log(time == "2 pm");
let mang = "nis";
console.log(mang == "piaic" ? "i predict " : "i predict ");
console.log(mang == "piaic");
let duration = "6 month";
console.log(duration == "1 year" ? "i predict true" : "i predict false");
console.log(duration == "1 year");
